---
channel: stable
addons:
  signal_messenger:
    repository: TheBlackMini/signal-addon
    target: signal
    image: ghcr.io/haberda/signal_messenger/{arch}
  jackett:
    repository: TheBlackMini/jackett-addon
    target: jackett
    image: ghcr.io/haberda/jackett/{arch}
